- src/coins/coins.ts
DAI exists on Base Chain now, we want to have it in our base tokens
> feat(coins): add DAI to Base chain

- src/coins/coins.ts
Token contract on explorer: https://zkevm.polygonscan.com/token/0x1e4a5963abfd975d8c9021ce480b42188849d41d
> feat: add usdt on polygon zkevm era chain

- src/chains/supportedChains.ts
Our current MOR and MOO RPCs fail sometimes, we'd like to have more stable RPCs.
> chore(rpc): add more MOR and MOO RPCs

- src/coins/coins.ts
> chore: update sushi logo

- src/coins/coins.ts
Doc about USDT on zkEVM era: https://explorer.zksync.io/tokenlist
> fix: add usdt on zksync era

- src/coins/coins.ts
Jira Ticket:
https://lifi.atlassian.net/browse/LF-6753
What I didi:
Add base tokens for Metis Chain
- WETH: https://andromeda-explorer.metis.io/address/0x420000000000000000000000000000000000000A
- m.USDC: https://andromeda-explorer.metis.io/token/0xEA32A96608495e54156Ae48931A7c20f0dcc1a21/token-transfers
- m.DAI: https://andromeda-explorer.metis.io/token/0x4c078361FC9BbB78DF910800A991C7c3DD2F6ce0/token-transfers
- m.USDT: https://andromeda-explorer.metis.io/token/0xbB06DCA3AE6887fAbF931640f67cab3e3a16F4dC/token-transfers
> feat: add Metis base coins

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-7256
> feat: add Scroll base coins and chain information

- src/coins/coins.ts
I forgot to wrapped eth to wrappedGasonChain
> feat: Add wrapped gas on scroll

- README.md
> docs(README): improve documentation

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-7592
> feat: add mode coins and chain

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-8064
> feat: add support assets for Mantle chain

- package.json
- src/chains/supportedChains.evm.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-8460
@lifi/types updates, we should update it accordingly
> fix: update mantle icon

- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
Chain info according to debank:
> feat: add Rootstock support

- package.json
- src/chains/supportedChains.evm.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-8050
> chore: update celo RPC and explorer, types

- package.json
- src/coins/coins.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-2324
> chore: add frxETH to basicCoins

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
Please note that: SEI EVM chain does not have wrapped token, native token is WSEI. WSEI in SEI EVM chain is backed by SEI on SEI chain (not EVM)
> feat: add tokens

- src/coins/coins.ts
https://lifi.atlassian.net/browse/LF-8695
> fix: wrong logo for rbtc

- src/coins/coins.ts
https://lifi.atlassian.net/browse/LF-8705
> chore: add usdce on gnosis

- src/coins/coins.ts
Reverts lifinance/data-types#47
> Revert "chore: add usdce on gnosis"

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
- Update the version of lifi/types
- Update the multicall contract
- Update token and wrapped token
> feat: add fraxtal chain and token support

- src/coins/coins.ts
Update frax and frxETH token on SEI chain
> chore: add frx token to coins list

- src/coins/coins.ts
A quick update to token WG name
> fix: wrong token name

- CHANGELOG.md
- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-9390
> feat: add immutable-x chain

- package.json
- src/chains/supportedChains.evm.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-9706
> chore: update types version

- CHANGELOG.md
- package.json
- src/coins/coins.ts
https://lifi.atlassian.net/browse/LF-9833
SEI chain wanna wETH explicitly. Current wETH is fetched from Stargate bridge definition, named as wETH(Stargate). SEI wanna wETH to clear the confusion
> chore: add wETH on SEI chain

- package.json
- yarn.lock
> fix: update package version

- src/coins/coins.ts
https://kaiascan.io/address/0x6270b58be569a7c0b8f47594f191631ae5b2c86c?tabId=txList&page=1 
This usdc is used in 1inch
> feat: add usdc on kaiai

- package.json
- src/coins/coins.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-10136
> feat: add axlusdc coin

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
> feat: add new chain xlay

- src/coins/coins.ts
https://lifi.atlassian.net/browse/LF-11483
> feat: add wbtc on sei chain

- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-10932
> feat: add lisk token assets

- CHANGELOG.md
- package.json
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- yarn.lock
https://lifi.atlassian.net/browse/LF-11056
> feat: add new chain abstract

- package.json
- pnpm-lock.yaml
- src/chains/index.ts
- src/chains/supportedChains.mvm.int.spec.ts
- src/chains/supportedChains.mvm.ts
- src/chains/supportedChains.ts
- src/coins/coins.ts
- src/multicall.ts
https://lifi.atlassian.net/browse/LF-12043
- Add MVM chain support
- Add SUI chain & token data
- Add token data for some basic & wrapped tokens on SUI (ETH, BTC, SOL, USDC, USDT
> feat: Add MVM ecosystem and SUI chain

- src/chains/supportedChains.evm.ts
> fix: rename BERA -> Berachain

- package.json
- pnpm-lock.yaml
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
types: https://github.com/lifinance/types/pull/336
> feat(chains): add Lens

- CHANGELOG.md
- package.json
- pnpm-lock.yaml
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
- **feat(Chain): add Swell**
- **chore(release): 6.9.0-beta.0**
> feat(chain): add Swell

- src/chains/supportedChains.evm.ts
https://lifi.atlassian.net/browse/LF-13334
> chore: update abstract rpc

- src/coins/coins.ts
https://lifi.atlassian.net/browse/LF-13706
> fix(coins): rename USDCe on Sonic to USDC

- package.json
- pnpm-lock.yaml
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
> feat(chain): add XDC

- src/chains/supportedChains.evm.ts
https://lifi.atlassian.net/browse/LF-13881
> chore: update hyperevm RPC

- package.json
- pnpm-lock.yaml
https://lifi.atlassian.net/browse/LF-13212
> feat: enrich token

- package.json
- pnpm-lock.yaml
- src/coins/coins.ts
Updating several USDC(e/n) on request of ali/partners
> feat(coins): update several USDC's

- src/chains/supportedChains.evm.ts
The old explorer is dead, long live the new explorer
> fix(IMX): remove dead explorer url

- src/coins/coins.ts
> fix: remove duplicated frxETH

- src/coins/coins.ts
Plasma official team docs more deployed coins: USDe and USDT0
> feat: add more plasma tokens

- package.json
- pnpm-lock.yaml
- src/chains/foundry.ts
- src/chains/supportedChains.evm.ts
- src/coins/coins.ts
- src/multicall.ts
https://lifi.atlassian.net/browse/LF-15489
> feat: add flow chain
